package org.wahlzeit.model;

import java.sql.*;
import java.net.*;
import java.lang.Math.*;
import java.util.Objects;

import org.wahlzeit.services.*;
import org.wahlzeit.utils.*;

public class CartesianCoordinate extends AbstractCoordinate{

    private double x;
    private double y;
    private double z;

    public CartesianCoordinate(double x, double y, double z){
        //Preconditions: None, all Coordinates are valid
        this.x = x;
        this.y = y;
        this.z = z;
        //Postconditions: None
        assertClassInvariants();
    }

    public double getX(){
        //Preconditions: None
        //Postconditions: None
        assertClassInvariants();
        return x;
    }

    public double getY(){
        //Preconditions: None
        //Postconditions: None
        assertClassInvariants();
        return y;
    }

    public double getZ(){
        //Preconditions: None
        //Postconditions: None
        assertClassInvariants();
        return z;
    }

    public void setX(double x){
        assertClassInvariants();
        //Preconditions: None, all Coordinates are valid
        this.x = x;
        //Postconditions: None
        assertClassInvariants();
    }

    public void setY(double y){
        assertClassInvariants();
        //Preconditions: None, all Coordinates are valid
        this.y = y;
        //Postconditions: None
        assertClassInvariants();
    }

    public void setZ(double z){
        assertClassInvariants();
        //Preconditions: None, all Coordinates are valid
        this.z = z;
        //Postconditions: None
        assertClassInvariants();
    }

    @Override
    public boolean equals(Object o) {
        assertClassInvariants();
        //Preconditions: Object must not be null, Object Class must match own Class, Class Invariants of the Object must hold
        if (o == null) {
            return false;
        }

        if (o.getClass() != this.getClass()) {
            return false;
        }

        CartesianCoordinate compare = (CartesianCoordinate) o;
        //Since compare is not generated by a method asserting the Class Invariants, the check is necessary here
        compare.assertClassInvariants();

        //Postconditions: None
        return isEqual(compare);
    }

    @Override
    public CartesianCoordinate asCartesianCoordinate() {
        assertClassInvariants();
        //Preconditions: None
        //Postconditions: None
        return this;
    }

    @Override
    public SphericCoordinate asSphericCoordinate() {
        assertClassInvariants();
        //Preconditions: None
        //r = sqrt(x² + y² + z²)
        double r = Math.sqrt(x*x + y*y + z*z);
        //cos(theta) = z/r;
        double theta = Math.acos(z/r);
        //tan(phi) = y/x;
        double phi = Math.atan(y/x);
        SphericCoordinate converted = new SphericCoordinate(phi, theta, r);
        //Postconditions: None (Theoretically: New coordinate must be equal to the old coordinate)
        //HOWEVER: This leads to a Stackoverflow, as we cannot check if the new Coordinate is
        //Equal without calling a conversion method, which then again needs to make this assertion.
        //As such this postcondition is not asserted.
        return converted;
    }

    protected double doGetCartesianDistance(CartesianCoordinate c){
        //Assertion of Class Invariants is not necessary here, as they are already checked in
        //the conversion methods in the call of getCartesianDistance in AbstractCoordinate
        //Preconditions: None, check if argument is null is handled in getCartesianDistance
        //Postconditions: None
        return Math.sqrt(Math.pow(c.x - this.x, 2) + Math.pow(c.y - this.y, 2) + Math.pow(c.z - this.z, 2));
    }

    @Override
    public int hashCode(){
        assertClassInvariants();
        //Preconditions: None
        //Postconditions: None
        return Objects.hash(x, y, z);
    }

    @Override
    public boolean isEqual(Coordinate c) {
        assertClassInvariants();
        //Preconditions: None
        if(c == null) {
            return false;
        }
        CartesianCoordinate other = c.asCartesianCoordinate();
        if(Math.abs(other.x - this.x)>epsilon || Math.abs(other.y - this.y)>epsilon || Math.abs(other.z - this.z)>epsilon)return false;
        //Postconditions: None
        return true;
    }

    @Override
    public void assertClassInvariants() {
        //Any cartesian coordinate is valid, so there is no invariant to assert.
        //As such, this method as well as all calls to it are only here for completeness
    }
}